# Auto-Heal CI Agent configuration
# See: https://github.com/sidlabs-platform/Auto-Heal-CI-Agent

backend: copilot-cli
language: node

commit:
  mode: pr
  branch-prefix: auto-heal/

paths:
  allowed:
    - src/
    - tests/
  protected:
    - .github/
    - scripts/
    - .env

commands:
  lint: npm run lint
  test: npm test
  build: node -e "require('./src/app'); console.log('Build check passed');"
  install: npm ci

safety:
  max-attempts: 2
  dry-run: false
